name: todo-app server CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    defaults: 
      run:
        working-directory: ./server
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
      - name: Run tests
        run: npm test
        env:
          CI: true
          # APP_PORT: ${{secrets.APP_PORT}}
          # ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          # ACCESS_TOKEN_LIFE: ${{secrets.ACCESS_TOKEN_LIFE}}
          # SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
          # REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          # REFRESH_TOKEN_LIFE: ${{secrets.REFRESH_TOKEN_LIFE}}
          # MONGO_URI: ${{secrets.MONGO_URI}}
          # MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
