name: todo-app server CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./server
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo ${{ secrets }} >> .env
          cat .env
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
      - name: Run tests
        run: npm test
        env:
          CI: true
