name: todo-app server CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./server
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
      - name: Run tests
        run: npm test
        env:
          CI: true
